from django.conf.urls import url
from django.conf.urls import include

from . import views

from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('hello-viewset', views.HelloViewSet, base_name='hello-viewset')    #Registering a URl with our router that point towards our  HelloViewSet

urlpatterns = [
    url(r'^hello-view/', views.HelloApiView.as_view()),
    url(r'', include(router.urls))  #This way the router object creates the URLs for us and hence we need to include the URL generated by out router object.
]
